{{- $awsSecretsEnabled := and .Values.awsSecretsCSI (hasKey .Values.awsSecretsCSI "enabled") .Values.awsSecretsCSI.enabled -}}
{{- $awsEnvEnabled := and .Values.awsEnvSecret (hasKey .Values.awsEnvSecret "enabled") .Values.awsEnvSecret.enabled -}}
{{- if or $awsSecretsEnabled $awsEnvEnabled -}}
{{- $envPrefix := "prod" -}}
{{- if $awsSecretsEnabled -}}
  {{- $envPrefix = .Values.awsSecretsCSI.envPrefix | default "prod" -}}
{{- else if $awsEnvEnabled -}}
  {{- $envPrefix = .Values.awsEnvSecret.envPrefix | default "prod" -}}
{{- end -}}
{{- $secretsName := printf "%s/%s.secrets" $envPrefix (include "demo-app.fullname" .) -}}
{{- if and $awsSecretsEnabled .Values.awsSecretsCSI.secretName -}}
  {{- $secretsName = .Values.awsSecretsCSI.secretName -}}
{{- end -}}
{{- $secretsAlias := printf "%s.secrets" (include "demo-app.fullname" .) -}}
{{- if and $awsSecretsEnabled .Values.awsSecretsCSI.objectAlias -}}
  {{- $secretsAlias = .Values.awsSecretsCSI.objectAlias -}}
{{- end -}}
{{- $envEnvPrefix := "prod" -}}
{{- if $awsEnvEnabled -}}
  {{- $envEnvPrefix = .Values.awsEnvSecret.envPrefix | default "prod" -}}
{{- end -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "demo-app.fullname" . }}-aws-secrets
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    objects: |
      {{- if $awsSecretsEnabled }}
      - objectName: "{{ $secretsName }}"
        objectType: "secretsmanager"
        objectAlias: "{{ $secretsAlias }}"
        {{- if and .Values.awsSecretsCSI.jmesPath (gt (len .Values.awsSecretsCSI.jmesPath) 0) }}
        jmesPath:
          {{- range .Values.awsSecretsCSI.jmesPath }}
          - path: {{ .path | quote }}
            objectAlias: {{ .objectAlias | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- if $awsEnvEnabled }}
      - objectName: "{{ if .Values.awsEnvSecret.secretName }}{{ .Values.awsEnvSecret.secretName }}{{ else }}{{ $envEnvPrefix }}/{{ include "demo-app.fullname" . }}.env{{ end }}"
        objectType: "secretsmanager"
        objectAlias: "{{ include "demo-app.fullname" . }}.env"
      {{- end }}
{{- end }}
